//
// File generated by /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/root/5.34.18-x86_64-slc5-gcc4.3/bin/rootcint at Tue Apr  1 19:16:05 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdOdIStandAlonedIBCHCleaningToolCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BCHCleaningToolCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      namespace BCHTool {

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::BCHTool::BCHCleaningToolBase BCHCleaningToolBase;
      #else
      class BCHCleaningToolBase  {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~BCHCleaningToolBase() throw() {};
         bool m_isInit; //
         bool m_isData; //
         ::Root::TTileTripReader* m_tileTripReader; //
         ::TH1* m_h_inefficiency_lightq; //
         ::TH1* m_h_inefficiency_glu; //
         ::TH1* m_h_inefficiency_all; //
         ::TRandom3 m_rand; //
      };
      #endif
      } 
      namespace BCHTool {

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::BCHTool::BCHCleaningToolRoot BCHCleaningToolRoot;
      #else
      class BCHCleaningToolRoot  :  public ::BCHTool::BCHCleaningToolBase {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~BCHCleaningToolRoot() throw() {};
         :: TString m_toolName; //
      };
      #endif
      } 
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void BCHToolcLcLBCHCleaningToolBase_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void BCHToolcLcLBCHCleaningToolBase_Dictionary();
   static void delete_BCHToolcLcLBCHCleaningToolBase(void *p);
   static void deleteArray_BCHToolcLcLBCHCleaningToolBase(void *p);
   static void destruct_BCHToolcLcLBCHCleaningToolBase(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::BCHTool::BCHCleaningToolBase*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::BCHTool::BCHCleaningToolBase) == sizeof(::ROOT::Shadow::BCHTool::BCHCleaningToolBase));
      ::BCHTool::BCHCleaningToolBase *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BCHTool::BCHCleaningToolBase),0);
      static ::ROOT::TGenericClassInfo 
         instance("BCHTool::BCHCleaningToolBase", "./../BCHCleaningTool/BCHCleaningToolBase.h", 23,
                  typeid(::BCHTool::BCHCleaningToolBase), DefineBehavior(ptr, ptr),
                  &BCHToolcLcLBCHCleaningToolBase_ShowMembers, &BCHToolcLcLBCHCleaningToolBase_Dictionary, isa_proxy, 4,
                  sizeof(::BCHTool::BCHCleaningToolBase) );
      instance.SetDelete(&delete_BCHToolcLcLBCHCleaningToolBase);
      instance.SetDeleteArray(&deleteArray_BCHToolcLcLBCHCleaningToolBase);
      instance.SetDestructor(&destruct_BCHToolcLcLBCHCleaningToolBase);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::BCHTool::BCHCleaningToolBase*)
   {
      return GenerateInitInstanceLocal((::BCHTool::BCHCleaningToolBase*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BCHTool::BCHCleaningToolBase*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BCHToolcLcLBCHCleaningToolBase_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::BCHTool::BCHCleaningToolBase*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void BCHToolcLcLBCHCleaningToolRoot_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void BCHToolcLcLBCHCleaningToolRoot_Dictionary();
   static void *new_BCHToolcLcLBCHCleaningToolRoot(void *p = 0);
   static void *newArray_BCHToolcLcLBCHCleaningToolRoot(Long_t size, void *p);
   static void delete_BCHToolcLcLBCHCleaningToolRoot(void *p);
   static void deleteArray_BCHToolcLcLBCHCleaningToolRoot(void *p);
   static void destruct_BCHToolcLcLBCHCleaningToolRoot(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::BCHTool::BCHCleaningToolRoot*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::BCHTool::BCHCleaningToolRoot) == sizeof(::ROOT::Shadow::BCHTool::BCHCleaningToolRoot));
      ::BCHTool::BCHCleaningToolRoot *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BCHTool::BCHCleaningToolRoot),0);
      static ::ROOT::TGenericClassInfo 
         instance("BCHTool::BCHCleaningToolRoot", "./../BCHCleaningTool/BCHCleaningToolRoot.h", 14,
                  typeid(::BCHTool::BCHCleaningToolRoot), DefineBehavior(ptr, ptr),
                  &BCHToolcLcLBCHCleaningToolRoot_ShowMembers, &BCHToolcLcLBCHCleaningToolRoot_Dictionary, isa_proxy, 4,
                  sizeof(::BCHTool::BCHCleaningToolRoot) );
      instance.SetNew(&new_BCHToolcLcLBCHCleaningToolRoot);
      instance.SetNewArray(&newArray_BCHToolcLcLBCHCleaningToolRoot);
      instance.SetDelete(&delete_BCHToolcLcLBCHCleaningToolRoot);
      instance.SetDeleteArray(&deleteArray_BCHToolcLcLBCHCleaningToolRoot);
      instance.SetDestructor(&destruct_BCHToolcLcLBCHCleaningToolRoot);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::BCHTool::BCHCleaningToolRoot*)
   {
      return GenerateInitInstanceLocal((::BCHTool::BCHCleaningToolRoot*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BCHTool::BCHCleaningToolRoot*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BCHToolcLcLBCHCleaningToolRoot_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::BCHTool::BCHCleaningToolRoot*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void BCHToolcLcLBCHCleaningToolBase_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class BCHTool::BCHCleaningToolBase.
      typedef ::ROOT::Shadow::BCHTool::BCHCleaningToolBase ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::BCHTool::BCHCleaningToolBase*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_isInit", &sobj->m_isInit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_isData", &sobj->m_isData);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_tileTripReader", &sobj->m_tileTripReader);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_h_inefficiency_lightq", &sobj->m_h_inefficiency_lightq);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_h_inefficiency_glu", &sobj->m_h_inefficiency_glu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_h_inefficiency_all", &sobj->m_h_inefficiency_all);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_rand", &sobj->m_rand);
      R__insp.InspectMember(sobj->m_rand, "m_rand.");
   }

}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_BCHToolcLcLBCHCleaningToolBase(void *p) {
      delete ((::BCHTool::BCHCleaningToolBase*)p);
   }
   static void deleteArray_BCHToolcLcLBCHCleaningToolBase(void *p) {
      delete [] ((::BCHTool::BCHCleaningToolBase*)p);
   }
   static void destruct_BCHToolcLcLBCHCleaningToolBase(void *p) {
      typedef ::BCHTool::BCHCleaningToolBase current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BCHTool::BCHCleaningToolBase

//______________________________________________________________________________
namespace ROOT {
   void BCHToolcLcLBCHCleaningToolRoot_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class BCHTool::BCHCleaningToolRoot.
      typedef ::ROOT::Shadow::BCHTool::BCHCleaningToolRoot ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::BCHTool::BCHCleaningToolRoot*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_toolName", &sobj->m_toolName);
      R__insp.InspectMember(const_cast<  TString &>( sobj->m_toolName ), "m_toolName.");
      R__insp.GenericShowMembers("BCHTool::BCHCleaningToolBase", ( ::BCHTool::BCHCleaningToolBase * )( (::BCHTool::BCHCleaningToolRoot*) obj ), false);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_BCHToolcLcLBCHCleaningToolRoot(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCHTool::BCHCleaningToolRoot : new ::BCHTool::BCHCleaningToolRoot;
   }
   static void *newArray_BCHToolcLcLBCHCleaningToolRoot(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCHTool::BCHCleaningToolRoot[nElements] : new ::BCHTool::BCHCleaningToolRoot[nElements];
   }
   // Wrapper around operator delete
   static void delete_BCHToolcLcLBCHCleaningToolRoot(void *p) {
      delete ((::BCHTool::BCHCleaningToolRoot*)p);
   }
   static void deleteArray_BCHToolcLcLBCHCleaningToolRoot(void *p) {
      delete [] ((::BCHTool::BCHCleaningToolRoot*)p);
   }
   static void destruct_BCHToolcLcLBCHCleaningToolRoot(void *p) {
      typedef ::BCHTool::BCHCleaningToolRoot current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BCHTool::BCHCleaningToolRoot

/********************************************************
* ../StandAlone/BCHCleaningToolCint.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBCHCleaningToolCint();

extern "C" void G__set_cpp_environmentBCHCleaningToolCint() {
  G__cpp_reset_tagtableBCHCleaningToolCint();
}
#include <new>
extern "C" int G__cpp_dllrevBCHCleaningToolCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BCHTool::BCHCleaningToolBase */
static int G__BCHCleaningToolCint_582_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->InitializeTool((const bool) G__int(libp->para[0]), (Root::TTileTripReader*) G__int(libp->para[1])
, *((const string*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->InitializeTool((const bool) G__int(libp->para[0]), (Root::TTileTripReader*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCHCleaningToolCint_582_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->IsInMaskedRegion((const int) G__int(libp->para[0]), (const int) G__int(libp->para[1])
, (const double) G__double(libp->para[2]), (const double) G__double(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCHCleaningToolCint_582_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->IsBadLooseBCH(
(const int) G__int(libp->para[0]), (const int) G__int(libp->para[1])
, (const double) G__double(libp->para[2]), (const double) G__double(libp->para[3])
, (const double) G__double(libp->para[4]), (const double) G__double(libp->para[5])
, (const double) G__double(libp->para[6])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCHCleaningToolCint_582_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 8:
      G__letint(result7, 103, (long) ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->IsBadMediumBCH(
(const int) G__int(libp->para[0]), (const int) G__int(libp->para[1])
, (const double) G__double(libp->para[2]), (const double) G__double(libp->para[3])
, (const double) G__double(libp->para[4]), (const double) G__double(libp->para[5])
, (const double) G__double(libp->para[6]), (const int) G__int(libp->para[7])));
      break;
   case 7:
      G__letint(result7, 103, (long) ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->IsBadMediumBCH(
(const int) G__int(libp->para[0]), (const int) G__int(libp->para[1])
, (const double) G__double(libp->para[2]), (const double) G__double(libp->para[3])
, (const double) G__double(libp->para[4]), (const double) G__double(libp->para[5])
, (const double) G__double(libp->para[6])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCHCleaningToolCint_582_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->IsBadTightBCH(
(const int) G__int(libp->para[0]), (const int) G__int(libp->para[1])
, (const double) G__double(libp->para[2]), (const double) G__double(libp->para[3])
, (const double) G__double(libp->para[4]), (const double) G__double(libp->para[5])
, (const double) G__double(libp->para[6])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCHCleaningToolCint_582_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->IsBadLooseDeltaPhiJetMET(
(const int) G__int(libp->para[0]), (const int) G__int(libp->para[1])
, (const double) G__double(libp->para[2]), (const double) G__double(libp->para[3])
, (const double) G__double(libp->para[4]), (const double) G__double(libp->para[5])
, (const double) G__double(libp->para[6])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCHCleaningToolCint_582_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->IsBadMediumDeltaPhiJetMET(
(const int) G__int(libp->para[0]), (const int) G__int(libp->para[1])
, (const double) G__double(libp->para[2]), (const double) G__double(libp->para[3])
, (const double) G__double(libp->para[4]), (const double) G__double(libp->para[5])
, (const double) G__double(libp->para[6])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCHCleaningToolCint_582_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->IsBadTightDeltaPhiJetMET(
(const int) G__int(libp->para[0]), (const int) G__int(libp->para[1])
, (const double) G__double(libp->para[2]), (const double) G__double(libp->para[3])
, (const double) G__double(libp->para[4]), (const double) G__double(libp->para[5])
, (const double) G__double(libp->para[6])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCHCleaningToolCint_582_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->SetSeed((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((BCHTool::BCHCleaningToolBase*) G__getstructoffset())->SetSeed();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BCHTool::BCHCleaningToolBase G__TBCHToolcLcLBCHCleaningToolBase;
static int G__BCHCleaningToolCint_582_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BCHTool::BCHCleaningToolBase*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BCHTool::BCHCleaningToolBase*) (soff+(sizeof(BCHTool::BCHCleaningToolBase)*i)))->~G__TBCHToolcLcLBCHCleaningToolBase();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BCHTool::BCHCleaningToolBase*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BCHTool::BCHCleaningToolBase*) (soff))->~G__TBCHToolcLcLBCHCleaningToolBase();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BCHCleaningToolCint_582_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCHTool::BCHCleaningToolBase* dest = (BCHTool::BCHCleaningToolBase*) G__getstructoffset();
   *dest = *(BCHTool::BCHCleaningToolBase*) libp->para[0].ref;
   const BCHTool::BCHCleaningToolBase& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* BCHTool::BCHCleaningToolRoot */
static int G__BCHCleaningToolCint_583_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCHTool::BCHCleaningToolRoot* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCHTool::BCHCleaningToolRoot((const char*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) BCHTool::BCHCleaningToolRoot((const char*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new BCHTool::BCHCleaningToolRoot[n];
       } else {
         p = new((void*) gvp) BCHTool::BCHCleaningToolRoot[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new BCHTool::BCHCleaningToolRoot;
       } else {
         p = new((void*) gvp) BCHTool::BCHCleaningToolRoot;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCHCleaningToolCint_583_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((const BCHTool::BCHCleaningToolRoot*) G__getstructoffset())->GetName());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BCHCleaningToolCint_583_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BCHTool::BCHCleaningToolRoot* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BCHTool::BCHCleaningToolRoot(*(BCHTool::BCHCleaningToolRoot*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BCHTool::BCHCleaningToolRoot G__TBCHToolcLcLBCHCleaningToolRoot;
static int G__BCHCleaningToolCint_583_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BCHTool::BCHCleaningToolRoot*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BCHTool::BCHCleaningToolRoot*) (soff+(sizeof(BCHTool::BCHCleaningToolRoot)*i)))->~G__TBCHToolcLcLBCHCleaningToolRoot();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BCHTool::BCHCleaningToolRoot*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BCHTool::BCHCleaningToolRoot*) (soff))->~G__TBCHToolcLcLBCHCleaningToolRoot();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BCHTool::BCHCleaningToolBase */

/* BCHTool::BCHCleaningToolRoot */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBCHCleaningToolCint {
 public:
  G__Sizep2memfuncBCHCleaningToolCint(): p(&G__Sizep2memfuncBCHCleaningToolCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBCHCleaningToolCint::*p)();
};

size_t G__get_sizep2memfuncBCHCleaningToolCint()
{
  G__Sizep2memfuncBCHCleaningToolCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBCHCleaningToolCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot))) {
     BCHTool::BCHCleaningToolRoot *G__Lderived;
     G__Lderived=(BCHTool::BCHCleaningToolRoot*)0x1000;
     {
       BCHTool::BCHCleaningToolBase *G__Lpbase=(BCHTool::BCHCleaningToolBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot),G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolBase),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBCHCleaningToolCint() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("bitset<m_nBits>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_bitsetlE32gR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,std::pair<TString,unsigned int> >",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_maplETStringcOpairlETStringcOunsignedsPintgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOpairlETStringcOunsignedsPintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,pair<TString,unsigned int> >",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_maplETStringcOpairlETStringcOunsignedsPintgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOpairlETStringcOunsignedsPintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,pair<TString,unsigned int>,less<TString> >",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_maplETStringcOpairlETStringcOunsignedsPintgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOpairlETStringcOunsignedsPintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TripRegion>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlETripRegioncOallocatorlETripRegiongRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETripRegioncOallocatorlETripRegiongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlETripRegioncOallocatorlETripRegiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETripRegioncOallocatorlETripRegiongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlETripRegioncOallocatorlETripRegiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned short,unsigned int>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_maplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned short,unsigned int,less<unsigned short> >",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_maplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned int,std::map<unsigned short,unsigned int> >",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_maplEunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned int,map<unsigned short,unsigned int,less<unsigned short>,allocator<pair<const unsigned short,unsigned int> > > >",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_maplEunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned int,map<unsigned short,unsigned int,less<unsigned short>,allocator<pair<const unsigned short,unsigned int> > >,less<unsigned int> >",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_maplEunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BCHTool::BCHCleaningToolBase */
static void G__setup_memvarBCHToolcLcLBCHCleaningToolBase(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolBase));
   { BCHTool::BCHCleaningToolBase *p; p=(BCHTool::BCHCleaningToolBase*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"m_isInit=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"m_isData=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_RootcLcLTTileTripReader),-1,-1,2,"m_tileTripReader=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_TH1),-1,-1,2,"m_h_inefficiency_lightq=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_TH1),-1,-1,2,"m_h_inefficiency_glu=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_TH1),-1,-1,2,"m_h_inefficiency_all=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_TRandom3),-1,-1,2,"m_rand=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* BCHTool::BCHCleaningToolRoot */
static void G__setup_memvarBCHToolcLcLBCHCleaningToolRoot(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot));
   { BCHTool::BCHCleaningToolRoot *p; p=(BCHTool::BCHCleaningToolRoot*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,1,G__get_linked_tagnum(&G__BCHCleaningToolCintLN_TString),-1,-1,2,"m_toolName=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBCHCleaningToolCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBCHToolcLcLBCHCleaningToolBase(void) {
   /* BCHTool::BCHCleaningToolBase */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolBase));
   G__memfunc_setup("InitializeTool",1456,G__BCHCleaningToolCint_582_0_1, 121, -1, -1, 0, 3, 1, 1, 0, 
"g - - 10 - isData U 'Root::TTileTripReader' - 0 - tripReader "
"u 'string' - 10 '\"\"' MCInefficiencyFileName", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IsInMaskedRegion",1580,G__BCHCleaningToolCint_582_0_2, 103, -1, -1, 0, 4, 1, 1, 0, 
"i - - 10 - run i - - 10 - lbn "
"d - - 10 - eta d - - 10 - phi", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IsBadLooseBCH",1170,G__BCHCleaningToolCint_582_0_3, 103, -1, -1, 0, 7, 1, 1, 0, 
"i - - 10 - run i - - 10 - lbn "
"d - - 10 - eta d - - 10 - phi "
"d - - 10 - BCH_CORR_CELL d - - 10 - emfrac "
"d - - 10 - pt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IsBadMediumBCH",1265,G__BCHCleaningToolCint_582_0_4, 103, -1, -1, 0, 8, 1, 1, 0, 
"i - - 10 - run i - - 10 - lbn "
"d - - 10 - eta d - - 10 - phi "
"d - - 10 - BCH_CORR_CELL d - - 10 - emfrac "
"d - - 10 - pt i - - 10 '0' isUp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IsBadTightBCH",1168,G__BCHCleaningToolCint_582_0_5, 103, -1, -1, 0, 7, 1, 1, 0, 
"i - - 10 - run i - - 10 - lbn "
"d - - 10 - eta d - - 10 - phi "
"d - - 10 - BCH_CORR_CELL d - - 10 - emfrac "
"d - - 10 - pt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IsBadLooseDeltaPhiJetMET",2265,G__BCHCleaningToolCint_582_0_6, 103, -1, -1, 0, 7, 1, 1, 0, 
"i - - 10 - run i - - 10 - lbn "
"d - - 10 - eta d - - 10 - phi "
"d - - 10 - deltaPhiJetMET d - - 10 - emfrac "
"d - - 10 - pt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IsBadMediumDeltaPhiJetMET",2360,G__BCHCleaningToolCint_582_0_7, 103, -1, -1, 0, 7, 1, 1, 0, 
"i - - 10 - run i - - 10 - lbn "
"d - - 10 - eta d - - 10 - phi "
"d - - 10 - deltaPhiJetMET d - - 10 - emfrac "
"d - - 10 - pt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IsBadTightDeltaPhiJetMET",2263,G__BCHCleaningToolCint_582_0_8, 103, -1, -1, 0, 7, 1, 1, 0, 
"i - - 10 - run i - - 10 - lbn "
"d - - 10 - eta d - - 10 - phi "
"d - - 10 - deltaPhiJetMET d - - 10 - emfrac "
"d - - 10 - pt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetSeed",685,G__BCHCleaningToolCint_582_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 '1234' seed", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddTileTripReaderBoundaries",2709,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ResetTileTripReaderBoundaries",2959,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMCInefficiencyHistograms",2729,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "u 'string' - 11 - MCInefficiencyFileName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsInCore",764,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 4, 1, 2, 0, 
"i - - 10 - run i - - 10 - lbn "
"d - - 10 - eta d - - 10 - phi", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsInEdge",744,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 4, 1, 2, 0, 
"i - - 10 - run i - - 10 - lbn "
"d - - 10 - eta d - - 10 - phi", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BadCoreCut",956,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 3, 1, 2, 0, 
"d - - 10 - BCH_CORR_CELL d - - 10 - emfrac "
"d - - 10 - pt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BadEdgeCut",936,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 4, 1, 2, 0, 
"d - - 10 - BCH_CORR_CELL d - - 10 - emfrac "
"d - - 10 - pt i - - 10 '0' isUp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BadCoreCut_DeltaPhi",1830,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 2, 1, 2, 0, 
"d - - 10 - deltaPhiJetMET d - - 10 - emfrac", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BadEdgeCut_DeltaPhi",1810,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 2, 1, 2, 0, 
"d - - 10 - deltaPhiJetMET d - - 10 - emfrac", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FileExists",1024,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 1, 1, 2, 8, "u 'string' - 11 - filePath", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RequireFileToExist",1837,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 2, 0, 
"u 'string' - 11 - filePath C - - 10 - callingFunctionName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHisto",807,(G__InterfaceMethod) NULL, 85, G__get_linked_tagnum(&G__BCHCleaningToolCintLN_TH1), -1, 0, 3, 1, 2, 0, 
"U 'TFile' - 0 - file u 'TString' - 0 - hname "
"u 'TString' - 0 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPathFromFileName",1858,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__BCHCleaningToolCintLN_string), -1, 0, 1, 1, 2, 1, "u 'string' - 11 - fileName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Terminate",937,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 2, 0, 
"C - - 10 - caller C - - 10 - message", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("Warning",726,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 2, 8, 
"C - - 10 - caller C - - 10 - message", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("Info",396,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 2, 8, 
"C - - 10 - caller C - - 10 - message", (char*)NULL, (void*) NULL, 3);
   // automatic destructor
   G__memfunc_setup("~BCHCleaningToolBase", 1925, G__BCHCleaningToolCint_582_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BCHCleaningToolCint_582_0_28, (int) ('u'), G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolBase), -1, 1, 1, 1, 1, 0, "u 'BCHTool::BCHCleaningToolBase' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncBCHToolcLcLBCHCleaningToolRoot(void) {
   /* BCHTool::BCHCleaningToolRoot */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot));
   G__memfunc_setup("BCHCleaningToolRoot",1840,G__BCHCleaningToolCint_583_0_1, 105, G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot), -1, 0, 1, 1, 1, 0, "C - - 10 '\"BCHCleaningToolRoot\"' toolName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetName",673,G__BCHCleaningToolCint_583_0_2, 67, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Terminate",937,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 2, 0, 
"C - - 10 - caller C - - 10 - message", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Warning",726,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 2, 8, 
"C - - 10 - caller C - - 10 - message", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Info",396,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 2, 8, 
"C - - 10 - caller C - - 10 - message", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("BCHCleaningToolRoot", 1840, G__BCHCleaningToolCint_583_0_6, (int) ('i'), G__get_linked_tagnum(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot), -1, 0, 1, 1, 1, 0, "u 'BCHTool::BCHCleaningToolRoot' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BCHCleaningToolRoot", 1966, G__BCHCleaningToolCint_583_0_7, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBCHCleaningToolCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBCHCleaningToolCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBCHCleaningToolCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BCHCleaningToolCintLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_Root = { "Root" , 110 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_bitsetlE32gR = { "bitset<32>" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_maplETStringcOpairlETStringcOunsignedsPintgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOpairlETStringcOunsignedsPintgRsPgRsPgRsPgR = { "map<TString,pair<TString,unsigned int>,less<TString>,allocator<pair<const TString,pair<TString,unsigned int> > > >" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_RootcLcLTTileTripReader = { "Root::TTileTripReader" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_vectorlETripRegioncOallocatorlETripRegiongRsPgR = { "vector<TripRegion,allocator<TripRegion> >" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETripRegioncOallocatorlETripRegiongRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TripRegion,allocator<TripRegion> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_maplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgR = { "map<unsigned short,unsigned int,less<unsigned short>,allocator<pair<const unsigned short,unsigned int> > >" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_maplEunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRsPgRsPgRsPgR = { "map<unsigned int,map<unsigned short,unsigned int,less<unsigned short>,allocator<pair<const unsigned short,unsigned int> > >,less<unsigned int>,allocator<pair<const unsigned int,map<unsigned short,unsigned int,less<unsigned short>,allocator<pair<const unsigned short,unsigned int> > > > > >" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_TRandom3 = { "TRandom3" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_BCHTool = { "BCHTool" , 110 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolBase = { "BCHTool::BCHCleaningToolBase" , 99 , -1 };
G__linked_taginfo G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot = { "BCHTool::BCHCleaningToolRoot" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBCHCleaningToolCint() {
  G__BCHCleaningToolCintLN_TString.tagnum = -1 ;
  G__BCHCleaningToolCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_string.tagnum = -1 ;
  G__BCHCleaningToolCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_Root.tagnum = -1 ;
  G__BCHCleaningToolCintLN_bitsetlE32gR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_maplETStringcOpairlETStringcOunsignedsPintgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOpairlETStringcOunsignedsPintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_RootcLcLTTileTripReader.tagnum = -1 ;
  G__BCHCleaningToolCintLN_vectorlETripRegioncOallocatorlETripRegiongRsPgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETripRegioncOallocatorlETripRegiongRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_maplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_maplEunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_TRandom3.tagnum = -1 ;
  G__BCHCleaningToolCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_TH1.tagnum = -1 ;
  G__BCHCleaningToolCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__BCHCleaningToolCintLN_TFile.tagnum = -1 ;
  G__BCHCleaningToolCintLN_BCHTool.tagnum = -1 ;
  G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolBase.tagnum = -1 ;
  G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBCHCleaningToolCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_TString);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_string);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_Root);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_bitsetlE32gR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_maplETStringcOpairlETStringcOunsignedsPintgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOpairlETStringcOunsignedsPintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_RootcLcLTTileTripReader);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_vectorlETripRegioncOallocatorlETripRegiongRsPgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETripRegioncOallocatorlETripRegiongRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_maplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_maplEunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_TRandom3);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_TH1);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_TFile);
   G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_BCHTool);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolBase),sizeof(BCHTool::BCHCleaningToolBase),-1,263427,(char*)NULL,G__setup_memvarBCHToolcLcLBCHCleaningToolBase,G__setup_memfuncBCHToolcLcLBCHCleaningToolBase);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot),sizeof(BCHTool::BCHCleaningToolRoot),-1,263424,(char*)NULL,G__setup_memvarBCHToolcLcLBCHCleaningToolRoot,G__setup_memfuncBCHToolcLcLBCHCleaningToolRoot);
}
extern "C" void G__cpp_setupBCHCleaningToolCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupBCHCleaningToolCint()");
  G__set_cpp_environmentBCHCleaningToolCint();
  G__cpp_setup_tagtableBCHCleaningToolCint();

  G__cpp_setup_inheritanceBCHCleaningToolCint();

  G__cpp_setup_typetableBCHCleaningToolCint();

  G__cpp_setup_memvarBCHCleaningToolCint();

  G__cpp_setup_memfuncBCHCleaningToolCint();
  G__cpp_setup_globalBCHCleaningToolCint();
  G__cpp_setup_funcBCHCleaningToolCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBCHCleaningToolCint();
  return;
}
class G__cpp_setup_initBCHCleaningToolCint {
  public:
    G__cpp_setup_initBCHCleaningToolCint() { G__add_setup_func("BCHCleaningToolCint",(G__incsetup)(&G__cpp_setupBCHCleaningToolCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBCHCleaningToolCint() { G__remove_setup_func("BCHCleaningToolCint"); }
};
G__cpp_setup_initBCHCleaningToolCint G__cpp_setup_initializerBCHCleaningToolCint;

