/********************************************************************
* ../StandAlone/BCHCleaningToolCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../StandAlone/BCHCleaningToolCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBCHCleaningToolCint();
extern void G__cpp_setup_inheritanceBCHCleaningToolCint();
extern void G__cpp_setup_typetableBCHCleaningToolCint();
extern void G__cpp_setup_memvarBCHCleaningToolCint();
extern void G__cpp_setup_globalBCHCleaningToolCint();
extern void G__cpp_setup_memfuncBCHCleaningToolCint();
extern void G__cpp_setup_funcBCHCleaningToolCint();
extern void G__set_cpp_environmentBCHCleaningToolCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../BCHCleaningTool/BCHCleaningToolBase.h"
#include "../BCHCleaningTool/BCHCleaningToolRoot.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BCHCleaningToolCintLN_TString;
extern G__linked_taginfo G__BCHCleaningToolCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_string;
extern G__linked_taginfo G__BCHCleaningToolCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_Root;
extern G__linked_taginfo G__BCHCleaningToolCintLN_bitsetlE32gR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_maplETStringcOpairlETStringcOunsignedsPintgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOpairlETStringcOunsignedsPintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_RootcLcLTTileTripReader;
extern G__linked_taginfo G__BCHCleaningToolCintLN_vectorlETripRegioncOallocatorlETripRegiongRsPgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETripRegioncOallocatorlETripRegiongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_maplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_maplEunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_TRandom3;
extern G__linked_taginfo G__BCHCleaningToolCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_TH1;
extern G__linked_taginfo G__BCHCleaningToolCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__BCHCleaningToolCintLN_TFile;
extern G__linked_taginfo G__BCHCleaningToolCintLN_BCHTool;
extern G__linked_taginfo G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolBase;
extern G__linked_taginfo G__BCHCleaningToolCintLN_BCHToolcLcLBCHCleaningToolRoot;

/* STUB derived class for protected member access */
