/********************************************************************
* ../Root/TTileTripReaderCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../Root/TTileTripReaderCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTileTripReaderCint();
extern void G__cpp_setup_inheritanceTTileTripReaderCint();
extern void G__cpp_setup_typetableTTileTripReaderCint();
extern void G__cpp_setup_memvarTTileTripReaderCint();
extern void G__cpp_setup_globalTTileTripReaderCint();
extern void G__cpp_setup_memfuncTTileTripReaderCint();
extern void G__cpp_setup_funcTTileTripReaderCint();
extern void G__set_cpp_environmentTTileTripReaderCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../TileTripReader/TTileTripReader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTileTripReaderCintLN_vectorlEcharcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__TTileTripReaderCintLN_vectorlEcharcOallocatorlEchargRsPgRcLcLiterator;
extern G__linked_taginfo G__TTileTripReaderCintLN_reverse_iteratorlEvectorlEcharcOallocatorlEchargRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTileTripReaderCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TTileTripReaderCintLN_TChain;
extern G__linked_taginfo G__TTileTripReaderCintLN_TripRegion;
extern G__linked_taginfo G__TTileTripReaderCintLN_Root;
extern G__linked_taginfo G__TTileTripReaderCintLN_RootcLcLTTileTripReader;
extern G__linked_taginfo G__TTileTripReaderCintLN_RootcLcLTTileTripReadercLcLVerbosity;
extern G__linked_taginfo G__TTileTripReaderCintLN_vectorlETripRegioncOallocatorlETripRegiongRsPgR;
extern G__linked_taginfo G__TTileTripReaderCintLN_maplEunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOmaplEunsignedsPshortcOunsignedsPintcOlesslEunsignedsPshortgRcOallocatorlEpairlEconstsPunsignedsPshortcOunsignedsPintgRsPgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TTileTripReaderCintLN_vectorlEintcOallocatorlEintgRsPgR;

/* STUB derived class for protected member access */
typedef vector<char,allocator<char> > G__vectorlEcharcOallocatorlEchargRsPgR;
